CREATE DATABASE IF NOT EXISTS flight_game;
USE flight_game;

DROP TABLE IF EXISTS quizzes;
CREATE TABLE IF NOT EXISTS quizzes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question VARCHAR(255) NOT NULL,
    answer VARCHAR(255) NOT NULL,
    reward INT NOT NULL DEFAULT 100
);

INSERT INTO quizzes (question, answer, reward) VALUES
('What is the capital of Italy?', 'Rome', 100),
('What is the capital of France?', 'Paris', 100),
('What is the capital of Germany?', 'Berlin', 100),
('What is the capital of Spain?', 'Madrid', 100),
('What is the capital of Portugal?', 'Lisbon', 100),
('What is the capital of Netherlands?', 'Amsterdam', 100),
('What is the capital of Belgium?', 'Brussels', 100),
('What is the capital of Switzerland?', 'Bern', 100),
('What is the capital of Austria?', 'Vienna', 100),
('What is the capital of Poland?', 'Warsaw', 100),
('What is the capital of Czech Republic?', 'Prague', 100),
('What is the capital of Hungary?', 'Budapest', 100),
('What is the capital of Slovakia?', 'Bratislava', 100),
('What is the capital of Slovenia?', 'Ljubljana', 100),
('What is the capital of Croatia?', 'Zagreb', 100),
('What is the capital of Ireland?', 'Dublin', 100),
('What is the capital of United Kingdom?', 'London', 100),
('What is the capital of Norway?', 'Oslo', 100),
('What is the capital of Sweden?', 'Stockholm', 100),
('What is the capital of Finland?', 'Helsinki', 100),
('What is the capital of Denmark?', 'Copenhagen', 100),
('What is the capital of Iceland?', 'Reykjavik', 100),
('What is the capital of Greece?', 'Athens', 100),
('What is the capital of Turkey?', 'Ankara', 100),
('What is the capital of Russia?', 'Moscow', 100),
('What is the capital of Ukraine?', 'Kyiv', 100),
('What is the capital of Belarus?', 'Minsk', 100),
('What is the capital of Lithuania?', 'Vilnius', 100),
('What is the capital of Latvia?', 'Riga', 100),
('What is the capital of Estonia?', 'Tallinn', 100),
('What is the capital of Romania?', 'Bucharest', 100),
('What is the capital of Bulgaria?', 'Sofia', 100),
('What is the capital of Serbia?', 'Belgrade', 100),
('What is the capital of Montenegro?', 'Podgorica', 100),
('What is the capital of Kosovo?', 'Pristina', 100),
('What is the capital of North Macedonia?', 'Skopje', 100),
('What is the capital of Albania?', 'Tirana', 100),
('What is the capital of Bosnia and Herzegovina?', 'Sarajevo', 100),
('What is the capital of Moldova?', 'Chisinau', 100),
('What is the capital of Liechtenstein?', 'Vaduz', 100),
('What is the capital of Luxembourg?', 'Luxembourg', 100),
('What is the capital of Monaco?', 'Monaco', 100),
('What is the capital of San Marino?', 'San Marino', 100),
('What is the capital of Malta?', 'Valletta', 100),
('What is the capital of Andorra?', 'Andorra la Vella', 100),
('What is the capital of Vatican City?', 'Vatican City', 100),
('What is the capital of Morocco?', 'Rabat', 100),
('What is the capital of Algeria?', 'Algiers', 100),
('What is the capital of Tunisia?', 'Tunis', 100),
('What is the capital of Libya?', 'Tripoli', 100),
('What is the capital of Egypt?', 'Cairo', 100),
('What is the capital of Sudan?', 'Khartoum', 100),
('What is the capital of South Sudan?', 'Juba', 100),
('What is the capital of Mauritania?', 'Nouakchott', 100),
('What is the capital of Mali?', 'Bamako', 100),
('What is the capital of Niger?', 'Niamey', 100),
('What is the capital of Chad?', 'N\'Djamena', 100),
('What is the capital of Gambia?', 'Banjul', 100),
('What is the capital of Guinea?', 'Conakry', 100),
('What is the capital of Sierra Leone?', 'Freetown', 100),
('What is the capital of Liberia?', 'Monrovia', 100),
('What is the capital of Côte d’Ivoire?', 'Yamoussoukro', 100),
('What is the capital of Ghana?', 'Accra', 100),
('What is the capital of Togo?', 'Lomé', 100),
('What is the capital of Benin?', 'Porto-Novo', 100),
('What is the capital of Nigeria?', 'Abuja', 100),
('What is the capital of Cameroon?', 'Yaoundé', 100),
('What is the capital of Equatorial Guinea?', 'Malabo', 100),
('What is the capital of Gabon?', 'Libreville', 100),
('What is the capital of Republic of Congo?', 'Brazzaville', 100),
('What is the capital of Democratic Republic of Congo?', 'Kinshasa', 100),
('What is the capital of Angola?', 'Luanda', 100),
('What is the capital of Zambia?', 'Lusaka', 100),
('What is the capital of Malawi?', 'Lilongwe', 100),
('What is the capital of Mozambique?', 'Maputo', 100),
('What is the capital of Namibia?', 'Windhoek', 100),
('What is the capital of Botswana?', 'Gaborone', 100),
('What is the capital of Zimbabwe?', 'Harare', 100),
('What is the capital of South Africa?', 'Pretoria', 100),
('What is the capital of Lesotho?', 'Maseru', 100),
('What is the capital of Eswatini?', 'Mbabane', 100),
('What is the capital of Madagascar?', 'Antananarivo', 100),
('What is the capital of Seychelles?', 'Victoria', 100),
('What is the capital of Comoros?', 'Moroni', 100),
('What is the capital of Mauritius?', 'Port Louis', 100),
('What is the capital of Kenya?', 'Nairobi', 100),
('What is the capital of Tanzania?', 'Dodoma', 100),
('What is the capital of Uganda?', 'Kampala', 100),
('What is the capital of Rwanda?', 'Kigali', 100),
('What is the capital of Burundi?', 'Gitega', 100),
('What is the capital of Ethiopia?', 'Addis Ababa', 100),
('What is the capital of Djibouti?', 'Djibouti', 100),
('What is the capital of Somalia?', 'Mogadishu', 100),
('What is the capital of Eritrea?', 'Asmara', 100),
('What is the capital of Western Sahara?', 'El Aaiún', 100),
('What is the capital of Senegal?', 'Dakar', 100),
('What is the capital of Guinea-Bissau?', 'Bissau', 100),
('What is the capital of Central African Republic?', 'Bangui', 100),
('What is the capital of São Tomé and Príncipe?', 'São Tomé', 100),
('Which country is famous for the Great Wall?', 'China', 100),
('Where did the Renaissance begin?', 'Italy', 100),
('The Eiffel Tower is located in which city?', 'Paris', 100),
('Which ancient civilization built the Pyramids?', 'Egypt', 100),
('What is the traditional Japanese garment called?', 'Kimono', 100),
('Which country is known for the tango dance?', 'Argentina', 100),
('In which country is the city of Istanbul?', 'Turkey', 100),
('Which festival in India is known as the Festival of Lights?', 'Diwali', 100),
('What is the famous traditional dish of Spain with rice and seafood?', 'Paella', 100),
('Which European city is known for its canals and gondolas?', 'Venice', 100),
('In which country did the Olympic Games originate?', 'Greece', 100),
('The Statue of Liberty was gifted to the USA by which country?', 'France', 100),
('Which country is famous for tulips and windmills?', 'Netherlands', 100),
('Which city is known as the cultural capital of India?', 'Kolkata', 100),
('In which country is Machu Picchu located?', 'Peru', 100),
('Which festival celebrates the Chinese New Year?', 'Spring Festival', 100),
('Which country is famous for flamenco dance?', 'Spain', 100),
('The Opera House is a landmark in which city?', 'Sydney', 100),
('Which country is famous for sushi?', 'Japan', 100),
('Which city is known for the Louvre Museum?', 'Paris', 100),
('Which country celebrates Oktoberfest?', 'Germany', 100),
('Which African country is famous for pyramids of Meroë?', 'Sudan', 100),
('The Taj Mahal is located in which country?', 'India', 100),
('Which city hosts the Carnival festival in Brazil?', 'Rio de Janeiro', 100),
('Which country is famous for chocolate and waffles?', 'Belgium', 100),
('Which country is home to the Maori culture?', 'New Zealand', 100),
('Which festival in Thailand involves water fights?', 'Songkran', 100),
('The Colosseum is located in which city?', 'Rome', 100),
('Which country is known for reggae music?', 'Jamaica', 100),
('Which city is known for its jazz music heritage?', 'New Orleans', 100),
('Which country is famous for the tango and mate tea?', 'Argentina', 100),
('Which country is known for its fjords?', 'Norway', 100),
('Which country is famous for its tulip festival?', 'Netherlands', 100),
('Which country is home to the Maori Haka dance?', 'New Zealand', 100),
('Which city is known as the birthplace of opera?', 'Italy', 100),
('Which country is famous for the carnival of Venice?', 'Italy', 100),
('Which country celebrates Hanukkah?', 'Israel', 100),
('Which city is home to the Sagrada Familia?', 'Barcelona', 100),
('Which country is known for the samba dance?', 'Brazil', 100),
('Which country is famous for Oktoberfest beer festival?', 'Germany', 100),
('Which country is home to the Inca civilization?', 'Peru', 100),
('Which country is known for bagpipes music?', 'Scotland', 100),
('Which country celebrates Lunar New Year?', 'China', 100),
('Which country is famous for the Eiffel Tower?', 'France', 100),
('Which country is known for the Carnival of Rio?', 'Brazil', 100),
('Which city is home to the Acropolis?', 'Athens', 100),
('Which country is known for its sushi cuisine?', 'Japan', 100),
('Which country celebrates Bastille Day?', 'France', 100),
('Which country is home to the Great Wall?', 'China', 100),
('Which city is famous for its canals in Italy?', 'Venice', 100),
('Which country is known for kimono dress?', 'Japan', 100),
('Which country is famous for flamenco music and dance?', 'Spain', 100),
('Which country is famous for chocolate and pralines?', 'Belgium', 100),
('Which city is famous for its samba parades?', 'Rio de Janeiro', 100),
('Which country is famous for Diwali festival?', 'India', 100),
('Which country celebrates Songkran water festival?', 'Thailand', 100),
('Which country is famous for Oktoberfest beer festival?', 'Germany', 100),
('Which city hosts the Rio Carnival?', 'Rio de Janeiro', 100),
('Which country is famous for maple syrup?', 'Canada', 100),
('Which country is famous for sushi and tempura?', 'Japan', 100),
('Which country is famous for the Tango dance?', 'Argentina', 100),
('Which country is home to the Maasai tribe?', 'Kenya', 100),
('Which country is famous for reggae music?', 'Jamaica', 100),
('Which city is known for opera houses and symphonies?', 'Vienna', 100),
('Which country celebrates Holi festival?', 'India', 100),
('Which city is home to the Sydney Opera House?', 'Sydney', 100),
('Which country is famous for Mount Fuji?', 'Japan', 100),
('Which country celebrates Lunar New Year with dragon dances?', 'China', 100),
('Which country is famous for Sagrada Familia cathedral?', 'Spain', 100),
('Which country celebrates Bastille Day on July 14?', 'France', 100),
('Which country is known for Tango dance?', 'Argentina', 100),
('Which country is famous for Rio Carnival?', 'Brazil', 100),
('Which country is famous for Holi festival?', 'India', 100),
('Which country celebrates Songkran festival?', 'Thailand', 100),
('Which country is famous for Belgian waffles?', 'Belgium', 100),
('Which country is home to the Colosseum?', 'Italy', 100),
('Which country is famous for Flamenco dance?', 'Spain', 100),
('Which country is famous for Maple syrup?', 'Canada', 100),
('Which country is famous for Samba dance?', 'Brazil', 100),
('Which country is famous for Opera houses?', 'Austria', 100),
('Which country is famous for Sushi?', 'Japan', 100),
('Which country is famous for Paella?', 'Spain', 100),
('Which country is famous for Tango?', 'Argentina', 100),
('Which country celebrates Diwali?', 'India', 100),
('Which country celebrates Holi?', 'India', 100),
('Which country celebrates Songkran?', 'Thailand', 100),
('Which country is famous for Mount Fuji?', 'Japan', 100),
('Which country is famous for Opera?', 'Italy', 100),
('Which country is home to the Colosseum?', 'Italy', 100),
('Which country is known for Samba?', 'Brazil', 100),
('Which country celebrates Bastille Day?', 'France', 100),
('Which country celebrates Carnival?', 'Brazil', 100),
('Which country celebrates Mardi Gras?', 'USA', 100),
('Which country celebrates Day of the Dead?', 'Mexico', 100),
('Which country celebrates Hanami festival?', 'Japan', 100),
('Which country celebrates Lantern Festival?', 'China', 100),
('Which country celebrates Nowruz?', 'Iran', 100),
('In which year did the first man land on the Moon?', '1969', 100),
('How many continents are there on Earth?', '7', 100),
('How many planets are in the Solar System?', '8', 100),
('In which year did World War II end?', '1945', 100),
('What is the boiling point of water in Celsius?', '100', 100),
('How many states are there in the USA?', '50', 100),
('How many minutes are there in an hour?', '60', 100),
('How many seconds are there in a minute?', '60', 100),
('In which year was the United Nations founded?', '1945', 100),
('How many players are there in a football (soccer) team?', '11', 100),
('In which year did the Berlin Wall fall?', '1989', 100),
('How many months are there in a year?', '12', 100),
('How many days are there in a leap year?', '366', 100),
('What is the freezing point of water in Celsius?', '0', 100),
('In which year did the Titanic sink?', '1912', 100),
('How many Olympic rings are there?', '5', 100),
('How many hours are there in a day?', '24', 100),
('How many teeth does an adult human have?', '32', 100),
('In which year did the first iPhone release?', '2007', 100),
('How many players are there in a basketball team on the court?', '5', 100),
('How many bones are there in the adult human body?', '206', 100),
('How many stripes are there on the US flag?', '13', 100),
('In which year did the first World Cup take place?', '1930', 100),
('How many elements are in the periodic table?', '118', 100),
('How many letters are there in the English alphabet?', '26', 100),
('In which year did the French Revolution begin?', '1789', 100),
('How many Olympic sports were in the first modern Olympics?', '9', 100),
('In which year was Facebook founded?', '2004', 100),
('How many keys are there on a standard piano?', '88', 100),
('How many squares are there on a chessboard?', '64', 100),
('In which year did the Soviet Union collapse?', '1991', 100),
('How many kilometers are there in a marathon?', '42', 100),
('How many players are there in a rugby team?', '15', 100),
('In which year did the American Civil War start?', '1861', 100),
('How many countries are there in Africa?', '54', 100),
('How many stars are on the flag of the USA?', '50', 100),
('How many official languages does the UN have?', '6', 100),
('In which year did the Great Fire of London occur?', '1666', 100),
('How many legs does an octopus have?', '8', 100),
('How many sides does a hexagon have?', '6', 100),
('In which year did the first man-made satellite launch?', '1957', 100),
('How many Nobel Prize categories are there?', '6', 100),
('How many rings are there in the Olympic symbol?', '5', 100),
('In which year did the first modern Olympic Games take place?', '1896', 100),
('How many players are on a volleyball team on court?', '6', 100),
('How many stripes are on the flag of Germany?', '3', 100),
('How many provinces are there in Canada?', '10', 100),
('In which year was the Declaration of Independence signed?', '1776', 100),
('How many planets in the Solar System are classified as gas giants?', '4', 100),
('How many Great Lakes are there in North America?', '5', 100),
('In which year did the first man orbit the Earth?', '1961', 100),
('How many players are there in a cricket team?', '11', 100),
('How many moons does Earth have?', '1', 100),
('What is the capital of Canada?', 'Ottawa', 100),
('What is the capital of the United States?', 'Washington D.C.', 100),
('What is the capital of Mexico?', 'Mexico City', 100),
('What is the capital of Brazil?', 'Brasilia', 100),
('What is the capital of Argentina?', 'Buenos Aires', 100),
('What is the capital of Chile?', 'Santiago', 100),
('What is the capital of Peru?', 'Lima', 100),
('What is the capital of Colombia?', 'Bogota', 100),
('What is the capital of Venezuela?', 'Caracas', 100),
('What is the capital of Ecuador?', 'Quito', 100),
('What is the capital of Bolivia?', 'Sucre', 100),
('What is the capital of Paraguay?', 'Asuncion', 100),
('What is the capital of Uruguay?', 'Montevideo', 100),
('What is the capital of Guyana?', 'Georgetown', 100),
('What is the capital of Suriname?', 'Paramaribo', 100),
('What is the capital of French Guiana?', 'Cayenne', 100),
('What is the capital of Australia?', 'Canberra', 100),
('What is the capital of New Zealand?', 'Wellington', 100),
('What is the capital of Papua New Guinea?', 'Port Moresby', 100),
('What is the capital of Fiji?', 'Suva', 100),
('What is the capital of Solomon Islands?', 'Honiara', 100),
('What is the capital of Vanuatu?', 'Port Vila', 100),
('What is the capital of Samoa?', 'Apia', 100),
('What is the capital of Tonga?', 'Nuku\'alofa', 100),
('What is the capital of Kiribati?', 'Tarawa', 100),
('What is the capital of Micronesia?', 'Palikir', 100),
('What is the capital of Marshall Islands?', 'Majuro', 100),
('What is the capital of Nauru?', 'Yaren', 100),
('What is the capital of Tuvalu?', 'Funafuti', 100),
('What is the capital of Japan?', 'Tokyo', 100),
('What is the capital of South Korea?', 'Seoul', 100),
('What is the capital of North Korea?', 'Pyongyang', 100),
('What is the capital of China?', 'Beijing', 100),
('What is the capital of Taiwan?', 'Taipei', 100),
('What is the capital of Mongolia?', 'Ulaanbaatar', 100),
('What is the capital of Vietnam?', 'Hanoi', 100),
('What is the capital of Thailand?', 'Bangkok', 100),
('What is the capital of Myanmar?', 'Naypyidaw', 100),
('What is the capital of Cambodia?', 'Phnom Penh', 100),
('What is the capital of Laos?', 'Vientiane', 100),
('What is the capital of Malaysia?', 'Kuala Lumpur', 100),
('What is the capital of Singapore?', 'Singapore', 100),
('What is the capital of Indonesia?', 'Jakarta', 100),
('What is the capital of the Philippines?', 'Manila', 100),
('What is the capital of Brunei?', 'Bandar Seri Begawan', 100),
('What is the capital of India?', 'New Delhi', 100),
('What is the capital of Pakistan?', 'Islamabad', 100),
('What is the capital of Bangladesh?', 'Dhaka', 100),
('What is the capital of Nepal?', 'Kathmandu', 100),
('What is the capital of Bhutan?', 'Thimphu', 100),
('What is the capital of Sri Lanka?', 'Colombo', 100),
('What is the capital of Maldives?', 'Male', 100),
('What is the capital of Afghanistan?', 'Kabul', 100),
('What is the capital of Iran?', 'Tehran', 100),
('What is the capital of Iraq?', 'Baghdad', 100),
('What is the capital of Saudi Arabia?', 'Riyadh', 100),
('What is the capital of Yemen?', 'Sanaa', 100),
('What is the capital of Oman?', 'Muscat', 100),
('What is the capital of United Arab Emirates?', 'Abu Dhabi', 100),
('What is the capital of Qatar?', 'Doha', 100),
('What is the capital of Bahrain?', 'Manama', 100),
('What is the capital of Kuwait?', 'Kuwait City', 100),
('What is the capital of Jordan?', 'Amman', 100),
('What is the capital of Lebanon?', 'Beirut', 100),
('What is the capital of Syria?', 'Damascus', 100),
('What is the capital of Israel?', 'Jerusalem', 100),
('What is the capital of Palestine?', 'Ramallah', 100),
('What is the chemical symbol for water?', 'H2O', 100),
('What is the chemical symbol for oxygen?', 'O2', 100),
('What is the chemical symbol for carbon dioxide?', 'CO2', 100),
('What is the chemical symbol for gold?', 'Au', 100),
('What is the chemical symbol for silver?', 'Ag', 100),
('What is the chemical symbol for iron?', 'Fe', 100),
('What is the chemical symbol for copper?', 'Cu', 100),
('What is the chemical symbol for lead?', 'Pb', 100),
('What is the chemical symbol for mercury?', 'Hg', 100),
('What is the chemical symbol for sodium?', 'Na', 100),
('What is the largest planet in the Solar System?', 'Jupiter', 100),
('What is the smallest planet in the Solar System?', 'Mercury', 100),
('Which planet is known as the Red Planet?', 'Mars', 100),
('Which planet is known as the Blue Planet?', 'Earth', 100),
('Which planet has the most moons?', 'Jupiter', 100),
('Which planet is closest to the Sun?', 'Mercury', 100),
('Which planet is farthest from the Sun?', 'Neptune', 100),
('What is the name of the first satellite launched into space?', 'Sputnik 1', 100),
('Who was the first man to walk on the Moon?', 'Neil Armstrong', 100),
('Who was the first woman to go to space?', 'Valentina Tereshkova', 100),
('What is the speed of light in vacuum (approx)?', '300000 km/s', 100),
('What is the unit of force in the metric system?', 'Newton', 100),
('What is the unit of energy in the metric system?', 'Joule', 100),
('What is the unit of power in the metric system?', 'Watt', 100),
('What is the unit of electric current?', 'Ampere', 100),
('What is the unit of voltage?', 'Volt', 100),
('What is the unit of resistance?', 'Ohm', 100),
('Who developed the theory of relativity?', 'Albert Einstein', 100),
('Who discovered gravity?', 'Isaac Newton', 100),
('Who discovered penicillin?', 'Alexander Fleming', 100),
('Who invented the telephone?', 'Alexander Graham Bell', 100),
('Who invented the light bulb?', 'Thomas Edison', 100),
('Who invented the steam engine?', 'James Watt', 100),
('Who invented the airplane?', 'Wright Brothers', 100),
('Who invented the computer?', 'Charles Babbage', 100),
('Who invented the internet?', 'Tim Berners-Lee', 100),
('Who painted the Mona Lisa?', 'Leonardo da Vinci', 100),
('Who painted the Sistine Chapel ceiling?', 'Michelangelo', 100),
('Who painted Starry Night?', 'Vincent van Gogh', 100),
('Who painted The Last Supper?', 'Leonardo da Vinci', 100),
('Who wrote Romeo and Juliet?', 'William Shakespeare', 100),
('Who wrote Hamlet?', 'William Shakespeare', 100),
('Who wrote Macbeth?', 'William Shakespeare', 100),
('Who wrote the Harry Potter series?', 'J.K. Rowling', 100),
('Who wrote the Lord of the Rings?', 'J.R.R. Tolkien', 100),
('Who wrote 1984?', 'George Orwell', 100),
('Who wrote To Kill a Mockingbird?', 'Harper Lee', 100),
('Who wrote Pride and Prejudice?', 'Jane Austen', 100),
('Who wrote the Odyssey?', 'Homer', 100),
('Who wrote the Iliad?', 'Homer', 100),
('Who composed Beethoven\'s Fifth Symphony?', 'Ludwig van Beethoven', 100),
('Who composed Fur Elise?', 'Ludwig van Beethoven', 100),
('Who composed Mozart\'s Requiem?', 'Wolfgang Amadeus Mozart', 100),
('Who composed The Four Seasons?', 'Antonio Vivaldi', 100),
('Who composed Swan Lake?', 'Pyotr Ilyich Tchaikovsky', 100),
('Who composed The Nutcracker?', 'Pyotr Ilyich Tchaikovsky', 100),
('What is the largest ocean on Earth?', 'Pacific Ocean', 100),
('What is the smallest ocean on Earth?', 'Arctic Ocean', 100),
('What is the largest continent on Earth?', 'Asia', 100),
('What is the smallest continent on Earth?', 'Australia', 100),
('What is the longest river in the world?', 'Nile', 100),
('What is the largest river in the world by volume?', 'Amazon', 100),
('What is the highest mountain in the world?', 'Mount Everest', 100),
('What is the deepest ocean trench?', 'Mariana Trench', 100),
('What is the largest desert in the world?', 'Sahara', 100),
('What is the largest lake in the world?', 'Caspian Sea', 100),
('What is the largest island in the world?', 'Greenland', 100),
('What is the smallest country in the world?', 'Vatican City', 100),
('What is the largest country in the world by area?', 'Russia', 100),
('What is the most populous country in the world?', 'China', 100),
('What is the official language of Brazil?', 'Portuguese', 100),
('What is the official language of Mexico?', 'Spanish', 100),
('What is the official language of Canada?', 'English and French', 100),
('What is the official language of India?', 'Hindi and English', 100),
('What is the official language of Japan?', 'Japanese', 100),
('What is the official language of South Korea?', 'Korean', 100),
('What is the official language of Germany?', 'German', 100),
('What is the official language of France?', 'French', 100),
('What is the official language of Spain?', 'Spanish', 100),
('What is the official language of Italy?', 'Italian', 100),
('What is the currency of the United States?', 'US Dollar', 100),
('What is the currency of the Eurozone?', 'Euro', 100),
('What is the currency of the United Kingdom?', 'British Pound', 100),
('What is the currency of Japan?', 'Yen', 100),
('What is the currency of China?', 'Yuan', 100),
('What is the currency of India?', 'Rupee', 100),
('What is the currency of Russia?', 'Ruble', 100),
('What is the currency of Brazil?', 'Real', 100),
('What is the currency of Canada?', 'Canadian Dollar', 100),
('What is the currency of Australia?', 'Australian Dollar', 100),
('In which year did World War I start?', '1914', 100),
('In which year did World War I end?', '1918', 100),
('Who was the leader of Nazi Germany during World War II?', 'Adolf Hitler', 100),
('Who was the Prime Minister of the UK during World War II?', 'Winston Churchill', 100),
('Who was the President of the USA during World War II?', 'Franklin D. Roosevelt', 100),
('Who was the leader of the Soviet Union during World War II?', 'Joseph Stalin', 100),
('What was the name of the atomic bomb dropped on Hiroshima?', 'Little Boy', 100),
('What was the name of the atomic bomb dropped on Nagasaki?', 'Fat Man', 100),
('In which year did the Cold War end?', '1991', 100),
('What is the name of the first human to travel to space?', 'Yuri Gagarin', 100),
('In which year was the first human heart transplant performed?', '1967', 100),
('Who developed the first polio vaccine?', 'Jonas Salk', 100),
('Who discovered the structure of DNA?', 'Watson and Crick', 100),
('What is the main component of air?', 'Nitrogen', 100),
('What percentage of air is oxygen?', '21%', 100),
('What is the pH of pure water?', '7', 100),
('What is the hardest natural substance on Earth?', 'Diamond', 100),
('What is the softest natural substance on Earth?', 'Talc', 100),
('What is the melting point of ice in Celsius?', '0', 100),
('What is the boiling point of ethanol in Celsius (approx)?', '78', 100),
('What is the color of chlorophyll?', 'Green', 100),
('What is the process by which plants make food?', 'Photosynthesis', 100),
('What is the main organ of the respiratory system?', 'Lungs', 100),
('What is the main organ of the circulatory system?', 'Heart', 100),
('What is the main organ of the nervous system?', 'Brain', 100),
('What is the main organ of the digestive system?', 'Stomach', 100),
('How many chambers does the human heart have?', '4', 100),
('What is the normal human body temperature in Celsius?', '37', 100),
('What is the normal human heart rate (resting) in beats per minute?', '60-100', 100),
('What is the largest organ in the human body?', 'Skin', 100),
('What is the smallest bone in the human body?', 'Stapes', 100),
('What is the largest bone in the human body?', 'Femur', 100),
('What is the name of the fluid that surrounds the brain and spinal cord?', 'Cerebrospinal fluid', 100),
('What is the name of the tube that connects the throat to the stomach?', 'Esophagus', 100),
('What is the name of the enzyme in saliva that breaks down starch?', 'Amylase', 100),
('What is the name of the pigment that gives blood its red color?', 'Hemoglobin', 100),
('What is the name of the protein that gives hair its structure?', 'Keratin', 100),
('What is the name of the process by which cells divide?', 'Mitosis', 100),
('What is the name of the process by which sex cells divide?', 'Meiosis', 100),
('What is the number of chromosomes in a human somatic cell?', '46', 100),
('What is the number of chromosomes in a human gamete?', '23', 100),
('What is the name of the first cloned mammal?', 'Dolly the Sheep', 100),
('In which year was Dolly the Sheep cloned?', '1996', 100),
('What is the name of the virus that causes COVID-19?', 'SARS-CoV-2', 100),
('In which year was COVID-19 declared a pandemic?', '2020', 100),
('What is the name of the vaccine developed by Pfizer and BioNTech for COVID-19?', 'BNT162b2', 100),
('What is the name of the vaccine developed by Moderna for COVID-19?', 'mRNA-1273', 100),
('What is the name of the vaccine developed by AstraZeneca for COVID-19?', 'AZD1222', 100),
('What is the name of the vaccine developed by Johnson & Johnson for COVID-19?', 'Janssen', 100),
('What is the name of the largest rainforest in the world?', 'Amazon Rainforest', 100),
('What is the name of the largest coral reef in the world?', 'Great Barrier Reef', 100),
('What is the name of the tallest mountain in North America?', 'Denali', 100),
('What is the name of the tallest mountain in South America?', 'Aconcagua', 100),
('What is the name of the tallest mountain in Europe?', 'Mount Elbrus', 100),
('What is the name of the tallest mountain in Africa?', 'Mount Kilimanjaro', 100),
('What is the name of the tallest mountain in Asia?', 'Mount Everest', 100),
('What is the name of the tallest mountain in Australia?', 'Mount Kosciuszko', 100),
('What is the name of the tallest mountain in Antarctica?', 'Vinson Massif', 100),
('What is the name of the longest river in Asia?', 'Yangtze', 100),
('What is the name of the longest river in Europe?', 'Volga', 100),
('What is the name of the longest river in Africa?', 'Nile', 100),
('What is the name of the longest river in North America?', 'Mississippi-Missouri', 100),
('What is the name of the longest river in South America?', 'Amazon', 100),
('What is the name of the longest river in Australia?', 'Murray-Darling', 100),
('What is the name of the largest lake in North America?', 'Lake Superior', 100),
('What is the name of the largest lake in South America?', 'Lake Titicaca', 100),
('What is the name of the largest lake in Europe?', 'Lake Ladoga', 100),
('What is the name of the largest lake in Africa?', 'Lake Victoria', 100),
('What is the name of the largest lake in Asia?', 'Caspian Sea', 100),
('What is the name of the largest lake in Australia?', 'Lake Eyre', 100),
('What is the name of the largest desert in Asia?', 'Gobi', 100),
('What is the name of the largest desert in North America?', 'Great Basin', 100),
('What is the name of the largest desert in South America?', 'Atacama', 100),
('What is the name of the largest desert in Australia?', 'Great Victoria', 100),
('What is the name of the largest desert in Europe?', 'Tabernas', 100),
('What is the name of the largest island in Asia?', 'Borneo', 100),
('What is the name of the largest island in Europe?', 'Great Britain', 100),
('What is the name of the largest island in Africa?', 'Madagascar', 100),
('What is the name of the largest island in North America?', 'Greenland', 100),
('What is the name of the largest island in South America?', 'Tierra del Fuego', 100),
('What is the name of the largest island in Australia?', 'Tasmania', 100),
('What is the name of the largest country in Europe by area?', 'Russia', 100),
('What is the name of the largest country in Africa by area?', 'Algeria', 100),
('What is the name of the largest country in North America by area?', 'Canada', 100),
('What is the name of the largest country in South America by area?', 'Brazil', 100),
('What is the name of the largest country in Asia by area?', 'Russia', 100),
('What is the name of the largest country in Australia by area?', 'Australia', 100),
('What is the name of the most populous city in the world?', 'Tokyo', 100),
('What is the name of the most populous city in China?', 'Shanghai', 100),
('What is the name of the most populous city in India?', 'Mumbai', 100),
('What is the name of the most populous city in the USA?', 'New York City', 100),
('What is the name of the most populous city in Brazil?', 'Sao Paulo', 100),
('What is the name of the most populous city in Japan?', 'Tokyo', 100),
('What is the name of the most populous city in Germany?', 'Berlin', 100),
('What is the name of the most populous city in France?', 'Paris', 100),
('What is the name of the most populous city in the UK?', 'London', 100),
('What is the name of the most populous city in Italy?', 'Rome', 100),
('What is the name of the tallest building in the world?', 'Burj Khalifa', 100),
('In which city is the Burj Khalifa located?', 'Dubai', 100),
('What is the height of the Burj Khalifa (approx)?', '828 meters', 100),
('What is the name of the second tallest building in the world?', 'Merdeka 118', 100),
('In which city is the Merdeka 118 located?', 'Kuala Lumpur', 100),
('What is the name of the third tallest building in the world?', 'Shanghai Tower', 100),
('In which city is the Shanghai Tower located?', 'Shanghai', 100),
('What is the name of the tallest building in the USA?', 'One World Trade Center', 100),
('In which city is the One World Trade Center located?', 'New York City', 100),
('What is the name of the tallest building in Europe?', 'Lakhta Center', 100),
('In which city is the Lakhta Center located?', 'St. Petersburg', 100),
('What is the name of the tallest building in Africa?', 'Iconic Tower', 100),
('In which city is the Iconic Tower located?', 'Cairo', 100),
('What is the name of the tallest building in South America?', 'Torre Gran Costanera', 100),
('In which city is the Torre Gran Costanera located?', 'Santiago', 100),
('What is the name of the tallest building in Australia?', 'Q1 Tower', 100),
('In which city is the Q1 Tower located?', 'Gold Coast', 100),
('What is the name of the largest shopping mall in the world?', 'Iran Mall', 100),
('In which city is the Iran Mall located?', 'Tehran', 100),
('What is the name of the largest shopping mall in the USA?', 'Mall of America', 100),
('In which city is the Mall of America located?', 'Bloomington', 100),
('What is the name of the largest shopping mall in Europe?', 'Westfield London', 100),
('In which city is the Westfield London located?', 'London', 100),
('What is the name of the largest shopping mall in Asia?', 'New South China Mall', 100),
('In which city is the New South China Mall located?', 'Dongguan', 100),
('What is the name of the largest shopping mall in Africa?', 'Gateway Theatre of Shopping', 100),
('In which city is the Gateway Theatre of Shopping located?', 'Durban', 100),
('What is the name of the largest shopping mall in South America?', 'Shopping Eldorado', 100),
('In which city is the Shopping Eldorado located?', 'Sao Paulo', 100),
('What is the name of the largest shopping mall in Australia?', 'Chadstone Shopping Centre', 100),
('In which city is the Chadstone Shopping Centre located?', 'Melbourne', 100),
('What is the name of the largest airport in the world by passenger traffic?', 'Hartsfield-Jackson Atlanta International Airport', 100),
('In which city is Hartsfield-Jackson Atlanta International Airport located?', 'Atlanta', 100),
('What is the name of the largest airport in the world by area?', 'King Fahd International Airport', 100),
('In which city is King Fahd International Airport located?', 'Dammam', 100),
('What is the name of the largest airport in Europe by passenger traffic?', 'Heathrow Airport', 100),
('In which city is Heathrow Airport located?', 'London', 100),
('What is the name of the largest airport in Asia by passenger traffic?', 'Beijing Capital International Airport', 100),
('In which city is Beijing Capital International Airport located?', 'Beijing', 100),
('What is the name of the largest airport in Africa by passenger traffic?', 'O.R. Tambo International Airport', 100),
('In which city is O.R. Tambo International Airport located?', 'Johannesburg', 100),
('What is the name of the largest airport in South America by passenger traffic?', 'Sao Paulo-Guarulhos International Airport', 100),
('In which city is Sao Paulo-Guarulhos International Airport located?', 'Sao Paulo', 100),
('What is the name of the largest airport in Australia by passenger traffic?', 'Sydney Kingsford Smith Airport', 100),
('In which city is Sydney Kingsford Smith Airport located?', 'Sydney', 100),
('What is the name of the largest port in the world by cargo volume?', 'Shanghai Port', 100),
('In which city is Shanghai Port located?', 'Shanghai', 100),
('What is the name of the largest port in the world by container traffic?', 'Shanghai Port', 100),
('What is the name of the largest port in Europe by cargo volume?', 'Rotterdam Port', 100),
('In which city is Rotterdam Port located?', 'Rotterdam', 100),
('What is the name of the largest port in North America by cargo volume?', 'Los Angeles Port', 100),
('In which city is Los Angeles Port located?', 'Los Angeles', 100),
('What is the name of the largest port in South America by cargo volume?', 'Santos Port', 100),
('In which city is Santos Port located?', 'Santos', 100),
('What is the name of the largest port in Africa by cargo volume?', 'Durban Port', 100),
('In which city is Durban Port located?', 'Durban', 100),
('What is the name of the largest port in Australia by cargo volume?', 'Port of Melbourne', 100),
('In which city is Port of Melbourne located?', 'Melbourne', 100),
('What is the name of the largest bridge in the world by length?', 'Danyang-Kunshan Grand Bridge', 100),
('In which country is the Danyang-Kunshan Grand Bridge located?', 'China', 100),
('What is the name of the longest suspension bridge in the world?', 'Akashi Kaikyo Bridge', 100),
('In which country is the Akashi Kaikyo Bridge located?', 'Japan', 100),
('What is the name of the longest cable-stayed bridge in the world?', 'Russky Bridge', 100),
('In which country is the Russky Bridge located?', 'Russia', 100),
('What is the name of the longest arch bridge in the world?', 'Chaotianmen Bridge', 100),
('In which country is the Chaotianmen Bridge located?', 'China', 100),
('What is the name of the longest truss bridge in the world?', 'Pont de Québec', 100),
('In which country is the Pont de Québec located?', 'Canada', 100),
('What is the name of the longest beam bridge in the world?', 'Lake Pontchartrain Causeway', 100),
('In which country is the Lake Pontchartrain Causeway located?', 'USA', 100),
('What is the name of the largest dam in the world by volume?', 'Three Gorges Dam', 100),
('In which country is the Three Gorges Dam located?', 'China', 100),
('What is the name of the largest dam in the world by power generation?', 'Three Gorges Dam', 100),
('What is the name of the largest dam in the world by height?', 'Jinping-I Dam', 100),
('In which country is the Jinping-I Dam located?', 'China', 100),
('What is the name of the largest dam in the world by reservoir volume?', 'Kariba Dam', 100),
('In which country is the Kariba Dam located?', 'Zimbabwe/Zambia', 100),
('What is the name of the largest dam in Europe by power generation?', 'Itaipu Dam', 100),
('In which country is the Itaipu Dam located?', 'Brazil/Paraguay', 100),
('What is the name of the largest dam in North America by power generation?', 'Grand Coulee Dam', 100),
('In which country is the Grand Coulee Dam located?', 'USA', 100),
('What is the name of the largest dam in Africa by power generation?', 'Aswan High Dam', 100),
('In which country is the Aswan High Dam located?', 'Egypt', 100),
('What is the name of the largest dam in Australia by power generation?', 'Snowy Mountains Hydroelectric Scheme', 100),
('In which country is the Snowy Mountains Hydroelectric Scheme located?', 'Australia', 100),
('What is the name of the largest stadium in the world by capacity?', 'Rungrado 1st of May Stadium', 100),
('In which country is the Rungrado 1st of May Stadium located?', 'North Korea', 100),
('What is the name of the largest stadium in the world by seating capacity?', 'Narendra Modi Stadium', 100),
('In which country is the Narendra Modi Stadium located?', 'India', 100),
('What is the name of the largest stadium in Europe by capacity?', 'Camp Nou', 100),
('In which country is the Camp Nou located?', 'Spain', 100),
('What is the name of the largest stadium in North America by capacity?', 'Michigan Stadium', 100),
('In which country is the Michigan Stadium located?', 'USA', 100),
('What is the name of the largest stadium in South America by capacity?', 'Maracanã Stadium', 100),
('In which country is the Maracanã Stadium located?', 'Brazil', 100),
('What is the name of the largest stadium in Africa by capacity?', 'FNB Stadium', 100),
('In which country is the FNB Stadium located?', 'South Africa', 100),
('What is the name of the largest stadium in Australia by capacity?', 'Melbourne Cricket Ground', 100),
('In which country is the Melbourne Cricket Ground located?', 'Australia', 100),
('What is the name of the largest museum in the world by area?', 'The Louvre', 100),
('In which city is The Louvre located?', 'Paris', 100),
('What is the name of the largest museum in the world by number of artifacts?', 'Smithsonian Institution', 100),
('In which city is the Smithsonian Institution located?', 'Washington D.C.', 100),
('What is the name of the largest museum in Europe by number of artifacts?', 'British Museum', 100),
('In which city is the British Museum located?', 'London', 100),
('What is the name of the largest museum in Asia by area?', 'National Museum of China', 100),
('In which city is the National Museum of China located?', 'Beijing', 100),
('What is the name of the largest museum in Africa by area?', 'Egyptian Museum', 100),
('In which city is the Egyptian Museum located?', 'Cairo', 100),
('What is the name of the largest museum in South America by area?', 'Museu Nacional do Brasil', 100),
('In which city is the Museu Nacional do Brasil located?', 'Rio de Janeiro', 100),
('What is the name of the largest museum in Australia by area?', 'National Museum of Australia', 100),
('In which city is the National Museum of Australia located?', 'Canberra', 100),
('What is the name of the largest library in the world by number of books?', 'Library of Congress', 100),
('In which city is the Library of Congress located?', 'Washington D.C.', 100),
('What is the name of the largest library in the world by area?', 'National Library of China', 100),
('In which city is the National Library of China located?', 'Beijing', 100),
('What is the name of the largest library in Europe by number of books?', 'British Library', 100),
('In which city is the British Library located?', 'London', 100),
('What is the name of the largest library in Asia by number of books?', 'National Library of China', 100),
('What is the name of the largest library in Africa by number of books?', 'National Library of South Africa', 100),
('In which city is the National Library of South Africa located?', 'Cape Town', 100),
('What is the name of the largest library in South America by number of books?', 'Biblioteca Nacional de Brasil', 100),
('In which city is the Biblioteca Nacional de Brasil located?', 'Rio de Janeiro', 100),
('What is the name of the largest library in Australia by number of books?', 'National Library of Australia', 100),
('In which city is the National Library of Australia located?', 'Canberra', 100),
('What is the name of the largest zoo in the world by number of species?', 'San Diego Zoo', 100),
('In which city is the San Diego Zoo located?', 'San Diego', 100),
('What is the name of the largest zoo in the world by area?', 'Henry Doorly Zoo', 100),
('In which city is the Henry Doorly Zoo located?', 'Omaha', 100),
('What is the name of the largest zoo in Europe by number of species?', 'Berlin Zoo', 100),
('In which city is the Berlin Zoo located?', 'Berlin', 100),
('What is the name of the largest zoo in Asia by number of species?', 'Beijing Zoo', 100),
('In which city is the Beijing Zoo located?', 'Beijing', 100),
('What is the name of the largest zoo in Africa by number of species?', 'Johannesburg Zoo', 100),
('In which city is the Johannesburg Zoo located?', 'Johannesburg', 100),
('What is the name of the largest zoo in South America by number of species?', 'Sao Paulo Zoo', 100),
('In which city is the Sao Paulo Zoo located?', 'Sao Paulo', 100),
('What is the name of the largest zoo in Australia by number of species?', 'Taronga Zoo', 100),
('In which city is the Taronga Zoo located?', 'Sydney', 100),
('What is the name of the largest aquarium in the world by volume?', 'Chimelong Ocean Kingdom', 100),
('In which city is the Chimelong Ocean Kingdom located?', 'Zhuhai', 100),
('What is the name of the largest aquarium in the world by number of species?', 'Georgia Aquarium', 100),
('In which city is the Georgia Aquarium located?', 'Atlanta', 100),
('What is the name of the largest aquarium in Europe by volume?', 'Oceanário de Lisboa', 100),
('In which city is the Oceanário de Lisboa located?', 'Lisbon', 100),
('What is the name of the largest aquarium in Asia by volume?', 'Chimelong Ocean Kingdom', 100),
('What is the name of the largest aquarium in Africa by volume?', 'Two Oceans Aquarium', 100),
('In which city is the Two Oceans Aquarium located?', 'Cape Town', 100),
('What is the name of the largest aquarium in South America by volume?', 'Aquário de São Paulo', 100),
('In which city is the Aquário de São Paulo located?', 'Sao Paulo', 100),
('What is the name of the largest aquarium in Australia by volume?', 'Sea Life Sydney Aquarium', 100),
('In which city is the Sea Life Sydney Aquarium located?', 'Sydney', 100),
('What is the name of the largest theme park in the world by attendance?', 'Magic Kingdom (Walt Disney World)', 100),
('In which city is the Magic Kingdom located?', 'Orlando', 100),
('What is the name of the second largest theme park in the world by attendance?', 'Disneyland Park (California)', 100),
('In which city is the Disneyland Park located?', 'Anaheim', 100),
('What is the name of the largest theme park in Europe by attendance?', 'Disneyland Paris', 100),
('In which city is Disneyland Paris located?', 'Marne-la-Vallée', 100),
('What is the name of the largest theme park in Asia by attendance?', 'Tokyo Disneyland', 100),
('In which city is Tokyo Disneyland located?', 'Urayasu', 100),
('What is the name of the largest theme park in Africa by attendance?', 'Gold Reef City', 100),
('In which city is Gold Reef City located?', 'Johannesburg', 100),
('What is the name of the largest theme park in South America by attendance?', 'Beto Carrero World', 100),
('In which city is Beto Carrero World located?', 'Penha', 100),
('What is the name of the largest theme park in Australia by attendance?', 'Dreamworld', 100),
('In which city is Dreamworld located?', 'Gold Coast', 100),
('What is the name of the largest botanical garden in the world by area?', 'Royal Botanic Gardens, Kew', 100),
('In which city is the Royal Botanic Gardens, Kew located?', 'London', 100),
('What is the name of the largest botanical garden in the world by number of species?', 'Royal Botanic Gardens, Kew', 100),
('What is the name of the largest botanical garden in Asia by area?', 'Beijing Botanical Garden', 100),
('In which city is the Beijing Botanical Garden located?', 'Beijing', 100),
('What is the name of the largest botanical garden in North America by area?', 'New York Botanical Garden', 100),
('In which city is the New York Botanical Garden located?', 'New York City', 100),
('What is the name of the largest botanical garden in South America by area?', 'Jardim Botânico do Rio de Janeiro', 100),
('In which city is the Jardim Botânico do Rio de Janeiro located?', 'Rio de Janeiro', 100),
('What is the name of the largest botanical garden in Africa by area?', 'Kirstenbosch National Botanical Garden', 100),
('In which city is the Kirstenbosch National Botanical Garden located?', 'Cape Town', 100),
('What is the name of the largest botanical garden in Australia by area?', 'Royal Botanic Gardens Victoria', 100),
('In which city is the Royal Botanic Gardens Victoria located?', 'Melbourne', 100),
('What is the name of the largest planetarium in the world by diameter?', 'Shanghai Astronomy Museum', 100),
('In which city is the Shanghai Astronomy Museum located?', 'Shanghai', 100),
('What is the name of the largest planetarium in the world by seating capacity?', 'Hayden Planetarium', 100),
('In which city is the Hayden Planetarium located?', 'New York City', 100),
('What is the name of the largest planetarium in Europe by diameter?', 'Planetario de Madrid', 100),
('In which city is the Planetario de Madrid located?', 'Madrid', 100),
('What is the name of the largest planetarium in Asia by diameter?', 'Shanghai Astronomy Museum', 100),
('What is the name of the largest planetarium in Africa by diameter?', 'Johannesburg Planetarium', 100),
('In which city is the Johannesburg Planetarium located?', 'Johannesburg', 100),
('What is the name of the largest planetarium in South America by diameter?', 'Planetário do Ibirapuera', 100),
('In which city is the Planetário do Ibirapuera located?', 'Sao Paulo', 100),
('What is the name of the largest planetarium in Australia by diameter?', 'Sydney Planetarium', 100),
('In which city is the Sydney Planetarium located?', 'Sydney', 100),
('What is the name of the largest observatory in the world by altitude?', 'Mauna Kea Observatory', 100),
('In which country is the Mauna Kea Observatory located?', 'USA (Hawaii)', 100),
('What is the name of the largest observatory in the world by mirror size?', 'Gran Telescopio Canarias', 100),
('In which country is the Gran Telescopio Canarias located?', 'Spain', 100),
('What is the name of the largest observatory in Europe by mirror size?', 'Gran Telescopio Canarias', 100),
('What is the name of the largest observatory in Asia by mirror size?', 'Large Sky Area Multi-Object Fiber Spectroscopic Telescope (LAMOST)', 100),
('In which country is LAMOST located?', 'China', 100),
('What is the name of the largest observatory in Africa by mirror size?', 'Southern African Large Telescope (SALT)', 100),
('In which country is SALT located?', 'South Africa', 100),
('What is the name of the largest observatory in South America by mirror size?', 'Gemini South Observatory', 100),
('In which country is Gemini South Observatory located?', 'Chile', 100),
('What is the name of the largest observatory in Australia by mirror size?', 'Anglo-Australian Telescope', 100),
('In which country is the Anglo-Australian Telescope located?', 'Australia', 100),
('What is the name of the largest laboratory in the world by area?', 'CERN', 100),
('In which country is CERN located?', 'Switzerland/France', 100);